import Link from "next/link";
import { notFound } from "next/navigation";
import { requireTeacher } from "@/src/lib/auth";
import { db } from "@/src/lib/db";
import { prePostDescriptor } from "@/src/lib/domain.mjs";

export default async function InsightDetail({params}:{params:Promise<{courseId:string;insightId:string}>}){
 const {courseId,insightId}=await params; const user=await requireTeacher();
 const insight=await db.aggregatedInsight.findFirst({where:{id:insightId,courseId,course:{teacherId:user.teacher.id}},include:{course:true,concept:true,recommendations:true}}); if(!insight) notFound();
 const latestAfter=await db.feedbackAggregate.findFirst({where:{courseId,conceptId:insight.conceptId},include:{session:true},orderBy:{generatedAt:"desc"}});
 const comparison=latestAfter?prePostDescriptor({beforeAffected:insight.affectedParticipants,beforeTotal:insight.totalParticipants,afterDoubt:latestAfter.stillDoubtCount,afterTotal:latestAfter.responseCount}):null;
 const evidence=Array.isArray(insight.evidenceJson)?insight.evidenceJson as string[]:[]; const explanations=Array.isArray(insight.explanationJson)?insight.explanationJson as Array<any>:[];
 return <div className="shell"><section className="hero"><Link className="link" href={`/teacher/courses/${courseId}`}>← {insight.course.name}</Link><div className="label">Detalle de insight</div><h1>{insight.concept.name}</h1><p>{insight.summary}</p></section>
 <div className="grid two"><section className="card"><h2>Qué tan extendida está</h2><div className="stat">{Math.round(insight.proportion*100)}%</div><p className="muted">{insight.affectedParticipants} de {insight.totalParticipants} estudiantes/conversaciones independientes muestran señales relacionadas.</p><span className={`badge ${insight.evidenceState==="SUFFICIENT"?"ok":"warn"}`}>{insight.evidenceState==="SUFFICIENT"?"Evidencia suficiente":"Datos insuficientes"}</span></section><section className="card"><h2>Qué podría hacer</h2>{insight.recommendations.length?insight.recommendations.map(r=><div key={r.id}><strong>{r.title}</strong><p>{r.actionText}</p><span className="badge">{r.status}</span></div>):<p className="muted">No se genera recomendación mientras la evidencia sea insuficiente.</p>}</section></div>
 <section className="section"><div className="section-title"><div><div className="label">Evidencia</div><h2>Ejemplos anonimizados</h2></div></div>{insight.evidenceState!=="SUFFICIENT"?<div className="notice warning">Todavía no hay suficiente evidencia para mostrar un patrón como hallazgo del grupo.</div>:evidence.length?<div className="stack">{evidence.map((e,i)=><div className="evidence" key={i}>“{e}”</div>)}</div>:<div className="empty">No hay snippets guardados para este insight.</div>}</section>
 <section className="section"><div className="section-title"><div><div className="label">Explicaciones observadas</div><h2>Qué parece estar ayudando</h2></div></div>{explanations.length?<div className="grid two">{explanations.map((e,i)=><div className="card" key={i}><strong>{String(e.type).replaceAll("_"," ").toLowerCase()}</strong><div className="small muted">Señal observada: {String(e.observedSignal).replaceAll("_"," ").toLowerCase()} · {e.count} ocurrencia/s</div></div>)}</div>:<div className="empty">Todavía no hay señales observables suficientes para asociar una forma de explicación con comprensión.</div>}</section>
 <section className="section"><div className="section-title"><div><div className="label">Antes / después</div><h2>Qué ocurrió después de intervenir</h2></div></div>{comparison&&latestAfter?<div className="card"><div className="grid two"><div><div className="label">Antes · conversaciones</div><div className="stat">{comparison.before.rate===null?"—":`${Math.round(comparison.before.rate*100)}%`}</div><div className="small muted">{comparison.before.affected}/{comparison.before.sample} conversaciones/estudiantes con señal de dificultad.</div></div><div><div className="label">Después · feedback · {latestAfter.session.title}</div><div className="stat">{comparison.after.rate===null?"—":`${Math.round(comparison.after.rate*100)}%`}</div><div className="small muted">{comparison.after.affected}/{comparison.after.sample} respuestas dicen que todavía hay dudas.</div></div></div><div className="notice warning" style={{marginTop:16}}><strong>Limitación:</strong> {comparison.limitation}</div></div>:<div className="empty">Todavía no hay feedback posterior para este concepto.</div>}</section></div>
}
