import Link from "next/link";
import { notFound } from "next/navigation";
import { requireTeacher } from "@/src/lib/auth";
import { db } from "@/src/lib/db";
import { planInterventionAction, renameInsightConceptAction, updateInsightStatusAction } from "../../../../../actions";
import { ConfirmSubmitButton, PendingSubmitButton } from "../../../../../components/ui-actions";

const evidenceLabels:Record<string,string>={SUFFICIENT:"Evidencia suficiente",INSUFFICIENT:"Evidencia insuficiente",NO_DATA:"Sin datos"};
const trendLabels:Record<string,string>={NEW:"Nuevo",RISING:"↑ En aumento",STABLE:"→ Estable",FALLING:"↓ En descenso"};
const statusLabels:Record<string,string>={OPEN:"Abierto",ACKNOWLEDGED:"Reconocido",ACTION_PLANNED:"Acción planificada",DISMISSED:"Descartado",RESOLVED:"Resuelto",MONITORING:"En seguimiento"};
const date=(value:Date|null)=>value?value.toLocaleString("es-AR",{dateStyle:"medium",timeStyle:"short"}):"No reconstruible";

function StatusForm({courseId,insightId,status,label,confirm}:{courseId:string;insightId:string;status:string;label:string;confirm?:string}){
 const fields=<><input type="hidden" name="courseId" value={courseId}/><input type="hidden" name="insightId" value={insightId}/><input type="hidden" name="status" value={status}/></>;
 return <form action={updateInsightStatusAction}>{fields}{confirm?<ConfirmSubmitButton message={confirm} className="btn ghost compact" pendingLabel="Actualizando…">{label}</ConfirmSubmitButton>:<PendingSubmitButton className="btn secondary compact" pendingLabel="Actualizando…">{label}</PendingSubmitButton>}</form>;
}

export default async function InsightDetail({params}:{params:Promise<{courseId:string;insightId:string}>}){
 const {courseId,insightId}=await params; const user=await requireTeacher();
 const insight=await db.aggregatedInsight.findFirst({where:{id:insightId,courseId,course:{teacherId:user.teacher.id}},include:{course:true,concept:true,recommendations:{orderBy:{createdAt:"desc"}},interventions:{orderBy:{createdAt:"desc"}}}}); if(!insight) notFound();
 const evidence=Array.isArray(insight.evidenceJson)?insight.evidenceJson as string[]:[];
 const sufficient=insight.evidenceState==="SUFFICIENT";
 return <div className="shell">
  <section className="course-header"><Link className="back-link" href={`/teacher/courses/${courseId}?view=insights`}>← Insights de {insight.course.name}</Link><div className="eyebrow">Insight pedagógico</div><h1>{insight.concept.name}</h1><p>{insight.summary}</p><div className="course-meta"><span className={`badge ${sufficient?"ok":"warn"}`}>{evidenceLabels[insight.evidenceState]}</span><span className="badge">{insight.trend?trendLabels[insight.trend]:"Tendencia aún no disponible"}</span><span className="badge gray">{statusLabels[insight.teacherStatus]}</span><span className="badge gray">{insight.affectedParticipants} participantes independientes</span></div></section>

  <section className="section card"><div className="section-subhead"><div><div className="label">Qué ocurre</div><h2>Resumen del patrón observado</h2></div></div><p>{insight.summary}</p></section>

  <details className="section card"><summary className="item-title">¿Por qué Educai muestra esto? <span className="link">Ver evidencia</span></summary><div className="grid two insight-evidence-metrics"><div><div className="label">Participantes independientes</div><strong>{insight.affectedParticipants} de {insight.totalParticipants}</strong></div><div><div className="label">Señales totales</div><strong>{insight.signalCount}</strong></div><div><div className="label">Reformulaciones</div><strong>{insight.reformulationCount}</strong></div><div><div className="label">Sesiones de estudio</div><strong>{insight.sessionCount}</strong></div><div><div className="label">Primera detección</div><strong>{date(insight.firstDetectedAt)}</strong></div><div><div className="label">Última detección</div><strong>{date(insight.lastDetectedAt)}</strong></div></div><div className="section-subhead"><div><h3>Ejemplos anonimizados</h3><p>Solo se exponen cuando hay evidencia grupal suficiente.</p></div></div>{!sufficient?<div className="notice warning"><strong>Ejemplos protegidos.</strong><span> La evidencia aún no supera el umbral de participantes independientes.</span></div>:evidence.length?<div className="stack">{evidence.map((item,index)=><blockquote className="evidence" key={index}>“{item}”</blockquote>)}</div>:<div className="empty compact"><strong>Sin ejemplos guardados</strong></div>}</details>

  <section className="section"><div className="section-title"><div><div className="label">Recomendación</div><h2>Qué podrías hacer</h2><p>Confirmá la propuesta o editá brevemente el texto antes de planificarla.</p></div></div>{insight.recommendations.length?<div className="stack">{insight.recommendations.map(r=><article className="card recommendation-card" key={r.id}><h3>{r.title}</h3><p>{r.rationale}</p><form action={planInterventionAction} className="form-stack"><input type="hidden" name="courseId" value={courseId}/><input type="hidden" name="recommendationId" value={r.id}/><div className="form-field"><label htmlFor={`action-${r.id}`}>Intervención para la próxima clase</label><textarea id={`action-${r.id}`} name="actualAction" defaultValue={r.actionText}/></div><PendingSubmitButton pendingLabel="Planificando…">Usar esta intervención</PendingSubmitButton></form></article>)}</div>:<div className="empty"><strong>Sin recomendación</strong><span>No se propone una acción hasta contar con evidencia suficiente.</span></div>}</section>

  <section className="section card"><div className="label">Decisión docente</div><h2>Actualizar estado</h2><div className="row"><StatusForm courseId={courseId} insightId={insightId} status="ACKNOWLEDGED" label="Reconocer"/><StatusForm courseId={courseId} insightId={insightId} status="MONITORING" label="Monitorear"/><StatusForm courseId={courseId} insightId={insightId} status="RESOLVED" label="Resolver"/><StatusForm courseId={courseId} insightId={insightId} status="DISMISSED" label="No representa el problema" confirm="¿Marcar este insight como descartado? La evidencia se conserva para auditoría."/><StatusForm courseId={courseId} insightId={insightId} status="DISMISSED" label="Descartar" confirm="¿Descartar este insight?"/></div><details><summary className="link">Cambiar concepto</summary><form action={renameInsightConceptAction} className="form-stack"><input type="hidden" name="courseId" value={courseId}/><input type="hidden" name="insightId" value={insightId}/><div className="form-field"><label htmlFor="conceptName">Nombre del concepto</label><input id="conceptName" name="conceptName" defaultValue={insight.concept.name} minLength={2} required/></div><PendingSubmitButton className="btn secondary" pendingLabel="Guardando…">Guardar concepto</PendingSubmitButton></form></details></section>
 </div>;
}
